### ISSUE TITLE
Register fail

### ISSUE THREAD

**Issue by jonastonny** [jonastonny/crs#14]
When register fails, fields are emptied. They should not be.

**Comment by jonastonny** [comment]
Jeg kan ikke lige finde nogen smart måde at gøre det på i Django - med mindre det hele skal laves som et post med Ajax.

**Comment by lomholdt** [comment]
Det er nemt nok, man sender bare værdierne med tilbage i formen! :) Det fikser vi hurtigt. Kan dog ikke se hvad problemet er. viewet er lavet rigtigt.
