### ISSUE TITLE
Hvis man lukker et rum, skal alle spørgmål så ikke også lukke?

### ISSUE THREAD

**Issue by lomholdt** [jonastonny/crs#27]

**Comment by jonastonny** [comment]
OnClose cascade

**Comment by jonastonny** [comment]
Kan Django selv finde ud af, når et rum skifter is_open at cascade samtlige set der tilhører og lukke hhv grupper og spørgsmål?

**Comment by lomholdt** [comment]
Tror faktisk vi kan lave en slags `GROUP ON UPDATE(is_open) CASCADE` agtig ting.
Men er ikke helt sikker på hvordan

**Comment by lomholdt** [comment]
Hm, tror faktisk ikke man kan på den måde. Tror vi skal lave en trigger, eller gøre det i koden.

**Comment by jonastonny** [comment]
Ja, fandt noget om "signals" i Django. Men er ikke sikker på det gør hvad vi ønsker.
